// Generated by https://quicktype.io

export interface RESTServiceEntity {
    error:  boolean;
    status: number;
    body:   BodyEntity[];
}

export interface BodyEntity {
    id:                 number;
    fecha:              null | string;
    hora:               null | string;
    id_tiposervicio:    number | null;
    id_placa:           null | number;
    id_conductorxplaca: null | number;
    id_cliente:         number | null;
    origen:             null | string;
    destino:            null | string;
    usuarios:           null | string;
    id_zona:            null | number;
    estado:             EstadoEntity | null;
    valor:              null | number;
    costo:              null | number;
    distancia:          null | number;
    duracion:           null | number;
    pesoinicial:        null | number;
    pesofinal:          null | number;
    observaciones:      null | string;
    usuariocrea:        null | string;
    fechacrea:          null | string;
}

export enum EstadoEntity {
    Solicitado = "solicitado",
}
