DROP PROCEDURE IF EXISTS OPERACIONES_TICKETS; 

DELIMITER //

CREATE PROCEDURE OPERACIONES_TICKETS(
	OPC VARCHAR(3),
	vIDTKT INT,
	vFECHA VARCHAR(10),
	vHORA VARCHAR(5),
	vID_SERVICIO int, 
	vID_CLIENTE int, 
	vDESCRIPCION TEXT, 
	vESTADO VARCHAR(10), 
	vPRIORIDAD VARCHAR(10), 
	vID_TIPOSERVICIO INT,
	vID_TECNICO INT
)
BEGIN
	
	IF OPC='NEW' THEN

		INSERT INTO TIKETS (FECHA, HORA, ID_SERVICIO, ID_CLIENTE, DESCRIPCION, ESTADO, PRIORIDAD, ID_TIPOSERVICIO) 
		VALUES(vFECHA, vHORA, vID_SERVICIO, vID_CLIENTE, vDESCRIPCION, vESTADO,vPRIORIDAD, vID_TIPOSERVICIO );
	
	ELSEIF OPC='UTC' THEN
		UPDATE TIKETS 
		SET ID_TECNICO = vID_TECNICO,
			ESTADO = 'ASIG'
		WHERE ID = vIDTKT;
	ELSE
		SELECT 'Opción no válida-OPERACIONES_TICKETS';
    	END IF;
END //
 
 DELIMITER ;