DROP PROCEDURE IF EXISTS SPMAESTROS; 

DELIMITER //

CREATE PROCEDURE SPMAESTROS(
	OPC VARCHAR(6)
)
BEGIN
	
	IF OPC='SERV' THEN
		SELECT ID, DESCRIPCION
		FROM SERVICIOS S
		WHERE ACTIVO = 1;
	
	ELSEIF OPC='TSRV' THEN
		SELECT ID, TIPOSERVICIO, DESCRIPCION
		FROM TIPOSERVICIO S
		WHERE ACTIVO = 1;
	ELSE
		SELECT 'Opción no válida- SPMAESTROS';
    	END IF;
END //
 
 DELIMITER ;