version: '3.8'

services:
  mysql:
    image: mysql:5.7 
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: meydtr
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123456
    volumes:
      ./mysql-data:/var/lib/mysql

  nodejs:
    image: back_tr
    container_name: back_tr_container
    restart: always
    ports:
      - "4000:80"
    depends_on:
      - mysql
